### ISSUE TITLE
Accidentally crash and need repair, then lose all configuration

### ISSUE THREAD

**Issue by Sraw** [crimx/ext-saladict#427]
### Saladict 版本

6.33.2

### 平台

Chrome 76.0.3809.87 (Official Build) (64-bit) On Linux Mint 19

### 类型

使用过程中当场Crash，在Extensions页面发现需要repair，repair后丢失所有配置项，需要重新配置。

### 重现方式

说实话我不知道怎么重现这个问题，我只是很简单地使用了一下词典，就是按住Ctrl然后选中翻译。

### 期待

其实Crash倒也无所谓，只是Repair之后丢失了所有的配置项比较糟心。当然会Crash肯定还是代码逻辑上有问题。不知道我能否提供什么信息供作者排查。

### 实际

实际上什么都没做，翻译窗口跳出来的一瞬间闪退了，然后就Crash了。

### 额外信息

以下是浏览器控制台的报错信息：
```
Failed to load resource: net::ERR_FAILED
content.js:1 Error: Extension context invalidated.
    at Object.render (content.js:1)
    at Ca (content.js:1)
    at Na (content.js:1)
    at so (content.js:1)
    at lo (content.js:1)
    at Qo (content.js:1)
    at Uo (content.js:1)
    at Ro (content.js:1)
    at Mo (content.js:1)
    at fo (content.js:1)
ja @ content.js:1
content.js:1 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Object.componentWillUnmount (chrome-extension://cdonnmffkdaoajfknoeeecmchibpmkmg/content.js:1:492377)
    at Ia (chrome-extension://cdonnmffkdaoajfknoeeecmchibpmkmg/content.js:1:220809)
    at La (chrome-extension://cdonnmffkdaoajfknoeeecmchibpmkmg/content.js:1:222284)
    at Xo (chrome-extension://cdonnmffkdaoajfknoeeecmchibpmkmg/content.js:1:231598)
    at Qo (chrome-extension://cdonnmffkdaoajfknoeeecmchibpmkmg/content.js:1:229522)
    at Uo (chrome-extension://cdonnmffkdaoajfknoeeecmchibpmkmg/content.js:1:228980)
    at Ro (chrome-extension://cdonnmffkdaoajfknoeeecmchibpmkmg/content.js:1:228806)
    at Mo (chrome-extension://cdonnmffkdaoajfknoeeecmchibpmkmg/content.js:1:228179)
    at fo (chrome-extension://cdonnmffkdaoajfknoeeecmchibpmkmg/content.js:1:227426)
    at Object.enqueueSetState (chrome-extension://cdonnmffkdaoajfknoeeecmchibpmkmg/content.js:1:202881)
ja @ content.js:1
content.js:1 Uncaught Error: Extension context invalidated.
    at Object.render (content.js:1)
    at Ca (content.js:1)
    at Na (content.js:1)
    at so (content.js:1)
    at lo (content.js:1)
    at Qo (content.js:1)
    at Uo (content.js:1)
    at Ro (content.js:1)
    at Mo (content.js:1)
    at fo (content.js:1)
content.js:1 Uncaught ReferenceError: browser is not defined
    at Object.<anonymous> (content.js:1)
    at n (content.js:1)
    at Object.<anonymous> (content.js:1)
    at n (content.js:1)
    at Object.<anonymous> (content.js:1)
    at n (content.js:1)
    at content.js:1
    at content.js:1
```

**Comment by crimx** [comment]
不好意思，不必按修复，请先关闭「查词面板」-「波形控制」。

**Comment by Sraw** [comment]
我默认应该是没有开启这个选项的。没记错的话这个选项以前是没有的，自动更新的话应该不会自动开启吧？

**Comment by crimx** [comment]
那这样有点奇怪，我一直没法复现这个问题。

Saladict7 面板的逻辑会重写，希望这个问题能解决掉。

**Comment by Sraw** [comment]
好的

**Comment by hwdd1992** [comment]
我也碰到了这个问题,今天也是频繁的崩溃.稍后补充详细信息

**Comment by crimx** [comment]
@hwdd1992 还会频繁崩溃吗，如果能够复现可以导出设置上传过来。

**Comment by crimx** [comment]
不知道显示的是不是 #432 中的信息，如果是的话我统一在那边更新情况。

**Comment by Sraw** [comment]
我倒是没有发生反复崩溃的现象，不清楚是否和他们的是一样的原因。不过显示的信息是一样的。如果作者觉得可以关闭此Issue也行。

**Comment by crimx** [comment]
应该是同个问题，奇怪的是我一次也没遇上，只能玄学修复。如果下个版本依然出现崩溃可以重开。
