### ISSUE TITLE
编译后缺少界面文字

### ISSUE THREAD

**Issue by KnIfER** [crimx/ext-saladict#944]
## Device info
 - Window10
 - chrome 83.0.4103.106 (正式版本) （64 位） (cohort: Stable)

 - Saladict  v7.14.5

- yarn1.22.4、npm@6.14.7、node v12.18.3

## Describe the bug

正常编译后，界面文字没有常显示，比如选项页，“基本选项”显示为 nav.General

## To Reproduce
依照 contribute 指示允许以下命令编译项目：
```
git clone……
yarn install
yarn pdf
yarn build
```
## Screenshots
![Screenshot (629)](https://user-images.githubusercontent.com/11593903/89293125-f78b7280-d68f-11ea-9ed7-e8cce39370f4.jpg)

**Comment by crimx** [comment]
命令看起来没有问题。是不是安装过程出错了？把 node_modules 删掉再装一遍试试？

**Comment by KnIfER** [comment]
试过了，删除目录下的node_modules没用

**Comment by crimx** [comment]
我干净环境下测试了一遍没问题的，而且火狐审核的时候也被审核员编译对比通过的。所以考虑是在某个步骤出了问题。

在浏览器 console 出现什么错误吗，包括设置页面以及 background 页面？

**Comment by KnIfER** [comment]
popup、background 都没有提示，
加载crx解压出来的是正常的，自己编译就不行，字符串没有编译到js文件中。

**Comment by crimx** [comment]
对了，你要 `yarn build --debug` 才会打印出调试信息，见 CONTRIBUTING.md。

扩展能够运行但是却无法加载翻译，我也想不出来什么问题会导致这样的情况。除了上面列出的步骤你没有额外做了修改吧？

**Comment by crimx** [comment]
你也可以运行 `yarn storybook` 以及 `yarn start --wextentry options` 看看有无问题。

**Comment by KnIfER** [comment]
没有修改，直接拉取源码编译的。
debug输出的是正常的信息。

**Comment by KnIfER** [comment]
yarn start --wextentry options：

![Screenshot (630)](https://upload-images.jianshu.io/upload_images/2253897-1a1f2620de56320d.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

（ERROR in xxx/dictionaries/xxx/requests.mock.ts）

还有
```
ERROR in ./test/specs/components/dictionaries/wikipedia/requests.mock.ts
Module not found: Error: Can't resolve './response/数字.html' in 'D:\salad\attempts\ext-saladict\test\specs\components\dictionaries\wikipedia'
 @ ./test/specs/components/dictionaries/wikipedia/requests.mock.ts 13:40-80
 @ ./test/specs/components/dictionaries sync ^\.\/.*\/requests\.mock\.ts$
 @ ./src/components/dictionaries/dictionaries.stories.tsx
 @ ./src sync \.stories\.tsx$
 @ ./.storybook/config.ts
 @ multi webextensions-emulator/dist/core ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.ts (webpack)-hot-middleware/client.js?reload=true

ERROR in ./test/specs/components/dictionaries/naver/requests.mock.ts
Module not found: Error: Can't resolve './response/爱.html' in 'D:\salad\attempts\ext-saladict\test\specs\components\dictionaries\naver'
 @ ./test/specs/components/dictionaries/naver/requests.mock.ts 12:73-112
 @ ./test/specs/components/dictionaries sync ^\.\/.*\/requests\.mock\.ts$
 @ ./src/components/dictionaries/dictionaries.stories.tsx
 @ ./src sync \.stories\.tsx$
 @ ./.storybook/config.ts
 @ multi webextensions-emulator/dist/core ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.ts (webpack)-hot-middleware/client.js?reload=true

Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  5.95 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core/dist/server/templates/index.ejs] 1.74 KiB {HtmlWebpackPlugin_0} [built]

WARN Broken build, fix the error below.
WARN You may need to refresh the browser.

```

**Comment by crimx** [comment]
先跑 `yarn fixtures` 下载测试数据。

debug 输出的“正常”信息方便贴一下么。

另外测试也是在 chrome 上跑的是吧，虽然火狐应该也没问题，但就问一问。

**Comment by KnIfER** [comment]
我全程录像了……
https://pan.baidu.com/s/1CxQ9OLZNNaDUnGvjC3qFmw
提取码1111
输出在“ EXT-SD_编译后首次运行.mp4”中

**Comment by KnIfER** [comment]
```
node scripts/fixtures.js
(node:9868) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'PROXY_HOST' of undefined
    at add (D:\Downloads\呕心沥血\ext-saladict-dev\scripts\fixtures.js:35:11)
    at main (D:\Downloads\呕心沥血\ext-saladict-dev\scripts\fixtures.js:28:5)
    at Object.<anonymous> (D:\Downloads\呕心沥血\ext-saladict-dev\scripts\fixtures.js:19:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
(node:9868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 0.42s.
```

**Comment by crimx** [comment]
感谢你的视频。我看了一遍，步骤都是没有问题的，所以我也是一头雾水。

猜测可能跟系统有关，但我现在手边没有 Windows 所以测试不了。

关于 `yarn fixtures` 报错，你有按 README 说明添加 `.env` 文件了么？也许跟这个也有关。

**Comment by KnIfER** [comment]
用子系统编译成功了……

**Comment by HumphreyDotSln** [comment]
同样的问题，WSL2编译出来就正常了

**Comment by actforjason** [comment]
同样错误，只能用子系统吗？

**Comment by actforjason** [comment]
@crimx 现在依旧有这个问题，有比较方便的解决方法吗？
